# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  candidateapi:
    image: candidateapi
    build:
      context: .
      dockerfile: Candidate.Api/Dockerfile
    ports:
      - 80:80
