USE [master]
GO
/****** Object:  Database [CandidateDB]    Script Date: 7/27/2023 6:25:17 PM ******/
CREATE DATABASE [CandidateDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CandidateDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\CandidateDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CandidateDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\CandidateDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [CandidateDB] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CandidateDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [CandidateDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [CandidateDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [CandidateDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [CandidateDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [CandidateDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [CandidateDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [CandidateDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [CandidateDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [CandidateDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [CandidateDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [CandidateDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [CandidateDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [CandidateDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [CandidateDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [CandidateDB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [CandidateDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [CandidateDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [CandidateDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [CandidateDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [CandidateDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [CandidateDB] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [CandidateDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [CandidateDB] SET RECOVERY FULL 
GO
ALTER DATABASE [CandidateDB] SET  MULTI_USER 
GO
ALTER DATABASE [CandidateDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [CandidateDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [CandidateDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [CandidateDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [CandidateDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [CandidateDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [CandidateDB] SET QUERY_STORE = ON
GO
ALTER DATABASE [CandidateDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [CandidateDB]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 7/27/2023 6:25:18 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[People]    Script Date: 7/27/2023 6:25:18 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[People](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](50) NOT NULL,
	[LastName] [nvarchar](50) NOT NULL,
	[PersonCode] [nvarchar](50) NOT NULL,
	[BasicSalary] [bigint] NOT NULL,
	[Allowance] [bigint] NOT NULL,
	[Transportation] [bigint] NOT NULL,
	[HoursWorked] [int] NOT NULL,
	[TotalSalary] [float] NOT NULL,
	[Date] [nvarchar](10) NOT NULL,
	[IsActive] [bit] NOT NULL,
	[IsDeleted] [bit] NOT NULL,
	[CreationDateTime] [datetime] NOT NULL,
	[ModificationDateTime] [datetime] NULL,
 CONSTRAINT [PK_People] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [CandidateDB] SET  READ_WRITE 
GO
